### ISSUE TITLE
Scan miniatures

### ISSUE THREAD

**Issue by LucasAzais** [LucasAzais/tts-aeon-trespass-odyssey#8]
### Primordials:
- [x] Hekaton
- [x] Temenos
- [x] Labyrinthauros
- [x] Hermesian Pursuer
- [x] Mini Pursuer
- [x] Cyclonus
- [x] Chimera Metastasios
- [x] The Nietzschean
- [x] The Burden
- [x] Mini Burden
- [x] Hypertime Oracle
- [x] Icarian Harpy
- [x] Sun Descendant

### Titans:
- [x] Ulyssea
- [x] Solon
- [x] Herodotus
- [x] Philoctera
- [x] Earthshaker
- [x] Mazerunner
- [x] Logicbreaker
- [x] Gamechanger
- [x] Warkeeper
- [x] Abysswatcher
- [x] Firestarter
- [x] Truthbearer
- [x] Ascender
- [x] Returner
- [x] Dawnburner

Other:
- [x] Argo Ship

**Comment by swittman** [comment]
I'll start with what's missing and then go back and redo the existing models so that everything's consistent.

**Comment by swittman** [comment]
Datasets have been collected for each model. The last Cycle 1 model is processing right now, with more than half of Cycles 2 and 3 already processed. Nothing has been textured yet. I did get one or two processing errors, so I may need to collect additional datasets on those models.

**Comment by swittman** [comment]
Cycle 1 is done.
